#
#__________.__                            .___        _____        __________.__               .__
#\______   \  | _____  ___.__. ___________|   | _____/ ____\____   \______   \  |  __ __  ____ |__| ____
# |     ___/  | \__  \<   |  |/ __ \_  __ \   |/    \   __\/  _ \   |     ___/  | |  |  \/ ___\|  |/    \
# |    |   |  |__/ __ \\___  \  ___/|  | \/   |   |  \  | (  <_> )  |    |   |  |_|  |  / /_/  >  |   |  \
# |____|   |____(____  / ____|\___  >__|  |___|___|  /__|  \____/   |____|   |____/____/\___  /|__|___|  /
#                    \/\/         \/               \/                                  /_____/         \/
#

Console_Command: "§cUse this command in-game"
NoPermission: "§cYou don't have permission to use that."
Player_Offline: "§cPlease enter a valid username."

Color_Text: "§9"
Prefix: "[§9PlayerInfo§f] "